// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SleepMaster",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "SleepMaster",
            targets: ["AppModule"],
            bundleIdentifier: "br.ufpe.cin.academy.acrn.SleepMaster",
            teamIdentifier: "9CSC9GA37T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .mic),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
